/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CmsAlign: typeof import('./src/components/Cms/CmsAlign.vue')['default']
    CmsAlignToggle: typeof import('./src/components/Cms/CmsAlignToggle.vue')['default']
    CmsArticle: typeof import('./src/components/Cms/CmsArticle.vue')['default']
    CmsButtonList: typeof import('./src/components/Cms/CmsButtonList.vue')['default']
    CmsContent: typeof import('./src/components/Cms/CmsContent.vue')['default']
    CmsEditor: typeof import('./src/components/Cms/CmsEditor.vue')['default']
    CmsFile: typeof import('./src/components/Cms/CmsFile.vue')['default']
    CmsGallery: typeof import('./src/components/Cms/CmsGallery.vue')['default']
    CmsImage: typeof import('./src/components/Cms/CmsImage.vue')['default']
    CmsItemList: typeof import('./src/components/Cms/CmsItemList.vue')['default']
    CmsLink: typeof import('./src/components/Cms/CmsLink.vue')['default']
    CmsQuote: typeof import('./src/components/Cms/CmsQuote.vue')['default']
    CmsRow: typeof import('./src/components/Cms/CmsRow.vue')['default']
    CmsSmallTitle: typeof import('./src/components/Cms/CmsSmallTitle.vue')['default']
    CmsTitle: typeof import('./src/components/Cms/CmsTitle.vue')['default']
    CmsYoutube: typeof import('./src/components/Cms/CmsYoutube.vue')['default']
    DataTable: typeof import('./src/components/DataTable/DataTable.vue')['default']
    EditFooter: typeof import('./src/components/EditFooter.vue')['default']
    FormActionFooter: typeof import('./src/components/Form/FormActionFooter.vue')['default']
    FormCheckbox: typeof import('./src/components/Form/FormCheckbox.vue')['default']
    FormCol: typeof import('./src/components/Form/FormCol.vue')['default']
    FormInput: typeof import('./src/components/Form/FormInput.vue')['default']
    FormInt: typeof import('./src/components/Form/FormInt.vue')['default']
    FormRadio: typeof import('./src/components/Form/FormRadio.vue')['default']
    FormSelect: typeof import('./src/components/Form/FormSelect.vue')['default']
    FormTextarea: typeof import('./src/components/Form/FormTextarea.vue')['default']
    FormTitle: typeof import('./src/components/Form/FormTitle.vue')['default']
    FormUpload: typeof import('./src/components/Form/FormUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
